[build]
builder = "NIXPACKS"
buildCommand = "cd vercel-ai-sdk-example && npm install -g pnpm && npx pnpm install && npx pnpm build"

[deploy]
startCommand = "cd vercel-ai-sdk-example && npx pnpm start" 