[project]
name = "mosaic-mcp"
version = "0.1.0"
description = "usemosaic.ai official mcp server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.6.1",
    "httpx>=0.28.1",
    "python-dotenv>=1.1.0",
    "python-magic-bin>=0.4.14",
]
